# -*- coding: utf-8 -*-
"""gw1.1-training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/148nJ2Y3N5TBjzrRm5oMElWM6QtAWiO9k

**pinn_models**
"""

import torch
print("CUDA available:", torch.cuda.is_available())
x = torch.randn(1000, 1000)
y = x.to('cuda')
z = y @ y
torch.cuda.synchronize()
print("GPU sanity check passed. Sum:", z.sum().item())

"""**CPU RUN WITH FIXED DF/DT SCALE AND GRADIENT CLIPPING**"""

"""
Combined, self-contained module: physics primitives + both PINN model
architectures. Merged into a single file so it runs cleanly in a single
Colab cell (importing from a second .py file fails in Colab unless that
file is separately written to disk first).

Sections:
  1. Physics primitives (torch, differentiable) -- was physics_pn_torch.py
  2. Model definitions -- was models.py

STRAIN_SCALE, mass ranges, and T_COALESCENCE all match the dataset generated
by 02_generate_dataset.py (4s @ 4096Hz, merger at t=3.5s).
"""

import torch
import torch.nn as nn


# =======================================================================
# SECTION 1: Physics primitives (differentiable torch port of physics_pn.py)
# =======================================================================

G = 6.674e-11
C = 2.998e8
MSUN_KG = 1.98892e30


def chirp_mass_to_kg(mchirp_msun):
    return mchirp_msun * MSUN_KG


def pn_dfdt(f, mchirp_msun):
    """Leading-order PN df/dt (Hz/s), differentiable w.r.t. both f and
    mchirp_msun. Shapes broadcast normally (e.g. f: [B, T], mchirp_msun: [B, 1])."""
    Mc = chirp_mass_to_kg(mchirp_msun)
    return (96.0 / 5.0) * torch.pi ** (8.0 / 3.0) * (G * Mc / C ** 3) ** (5.0 / 3.0) * f ** (11.0 / 3.0)


def pn_frequency_of_time(t, t_coalescence, mchirp_msun, f_max=400.0, tau_min=0.005):
    """Closed-form leading-order frequency-vs-time-to-merger track, with the
    numerical safeguards required for use inside a generator (see
    ARCHITECTURE_SPEC.md 3.3):
      - tau is floored at tau_min (5ms) to avoid the 1/tau singularity at t_c
      - f is capped at f_max (400 Hz) as a second line of defense

    t: [B, T] or [T] time grid (same for every sample in a batch, broadcastable)
    t_coalescence: python float (fixed constant for this dataset, not learned)
    mchirp_msun: [B, 1] predicted chirp mass per sample
    Returns: f(t), same shape as broadcast(t, mchirp_msun)
    """
    Mc = chirp_mass_to_kg(mchirp_msun)
    tau = t_coalescence - t
    tau_safe = torch.clamp(tau, min=tau_min)
    f = (1.0 / torch.pi) * (G * Mc / C ** 3) ** (-5.0 / 8.0) * (5.0 / (256.0 * tau_safe)) ** (3.0 / 8.0)
    f = torch.clamp(f, max=f_max)
    return f


def isco_frequency(total_mass_msun):
    Mtot = total_mass_msun * MSUN_KG
    return C ** 3 / (6.0 ** 1.5 * torch.pi * G * Mtot)


# ---------------------------------------------------------------------
# Differentiable instantaneous-frequency extraction (Hilbert transform via FFT)
# ---------------------------------------------------------------------

def instantaneous_frequency(strain, delta_t, smooth_kernel_width=25, hilbert_taps=201):
    """Estimate the instantaneous GW frequency of a real-valued strain
    signal via the analytic signal, followed by phase unwrap and a finite
    difference. Used by the soft model's physics residual on its OWN
    reconstructed strain, so every operation here must support autograd.

    strain: [B, T] real-valued tensor
    Returns: freq [B, T-1] (Hz), one shorter than input due to the
             finite-difference derivative

    GPU note: this function originally used torch.fft.fft/ifft to build
    the analytic signal (a real, standard technique). After hardening
    everything else in this pipeline (contiguity, NaN sanitization order,
    manual finite differences) and still hitting GPU-only illegal-memory-
    access / CUDNN_STATUS_EXECUTION_FAILED errors that never reproduced on
    CPU, the FFT/complex-autograd path was the one remaining exotic
    operation left unexamined -- complex-number autograd through cuFFT is
    a known historically fragile area across PyTorch/CUDA version
    combinations. It has been replaced with a fixed FIR Hilbert
    transformer (standard DSP technique: convolve with a windowed
    2/(pi*n) kernel), which uses only real-valued Conv1d -- the most
    heavily tested op in all of deep learning, and the same op already
    used elsewhere in this file without issue. Verified against a known
    50 Hz test signal: recovers 50.04-50.08 Hz (see changelog), an
    acceptable trade-off in accuracy for a large increase in robustness.
    """
    strain = strain.contiguous()
    strain = torch.nan_to_num(strain, nan=0.0, posinf=100.0, neginf=-100.0)  # defense in depth
    B, T = strain.shape

    # analytic signal via a fixed FIR Hilbert transformer (real conv1d only,
    # no FFT, no complex autograd)
    pad = hilbert_taps // 2
    n = torch.arange(-pad, pad + 1, device=strain.device, dtype=torch.float64)
    h = torch.zeros_like(n)
    odd_mask = (n.long() % 2 != 0)
    h[odd_mask] = -2.0 / (torch.pi * n[odd_mask])
    window = torch.hamming_window(hilbert_taps, periodic=False, dtype=torch.float64, device=strain.device)
    hilbert_kernel = (h * window).to(strain.dtype).view(1, 1, -1)

    strain_padded = torch.nn.functional.pad(strain.unsqueeze(1), (pad, pad), mode="replicate")
    hilbert_x = torch.nn.functional.conv1d(strain_padded.contiguous(), hilbert_kernel).squeeze(1).contiguous()

    phase = torch.atan2(hilbert_x, strain).contiguous()  # [B, T], wrapped to (-pi, pi]

    # differentiable phase unwrap: correct jumps > pi by adding/subtracting 2*pi,
    # implemented via cumulative sum of the wrapped jump correction (standard
    # np.unwrap algorithm, re-expressed with torch ops so it's differentiable).
    dphase = phase[:, 1:] - phase[:, :-1]
    dphase_wrapped = torch.remainder(dphase + torch.pi, 2 * torch.pi) - torch.pi
    correction = (dphase_wrapped - dphase).contiguous()
    phase_unwrapped = phase.clone()
    phase_unwrapped[:, 1:] = phase[:, 1:] + torch.cumsum(correction, dim=-1)
    phase_unwrapped = phase_unwrapped.contiguous()

    # manual finite difference instead of torch.gradient -- avoids relying
    # on torch.gradient's internal kernel behavior across torch/CUDA versions
    freq = (phase_unwrapped[:, 1:] - phase_unwrapped[:, :-1]) / (2 * torch.pi * delta_t)
    freq = freq.contiguous()

    # SANITIZE BEFORE the smoothing conv1d, not after. An untrained decoder
    # can produce near-arbitrary reconstructions, and raw finite-difference
    # frequency can be NaN/Inf as a result. 
    freq = torch.nan_to_num(freq, nan=0.0, posinf=2000.0, neginf=-2000.0)
    freq = torch.clamp(freq, min=-2000.0, max=2000.0).contiguous()

    
    # finite-difference noise, matching the rationale in Step 3 / ARCHITECTURE_SPEC 2.3
    if smooth_kernel_width > 1:
        kernel = torch.ones(1, 1, smooth_kernel_width, device=strain.device, dtype=strain.dtype) / smooth_kernel_width
        freq_padded = torch.nn.functional.pad(
            freq.unsqueeze(1), (smooth_kernel_width // 2, smooth_kernel_width // 2), mode="replicate")
        freq = torch.nn.functional.conv1d(freq_padded.contiguous(), kernel).squeeze(1)
        freq = freq[:, :phase_unwrapped.shape[1] - 1].contiguous()  # trim to match

    # final clamp to the physically sane band 
    freq = torch.nan_to_num(freq, nan=1.0, posinf=2000.0, neginf=1.0)
    freq = torch.clamp(torch.abs(freq), min=1.0, max=2000.0)
    return freq


# =======================================================================
# SECTION 2: Model definitions
# =======================================================================

STRAIN_SCALE = 1e21
T_COALESCENCE = 3.5          
MC_MIN, MC_MAX = 5.0, 40.0
MTOT_MIN, MTOT_MAX = 20.0, 80.0
A_MIN, A_MAX = 0.1, 10.0
PHYSICS_WINDOW_T = (3.42, 3.50)   
DFDT_SCALE = 20000.0  
DELTA_T = 1.0 / 4096


def _rescale_sigmoid(raw, lo, hi):
    return lo + torch.sigmoid(raw) * (hi - lo)


class SharedEncoder(nn.Module):
    """8 Conv1d blocks (kernel=15, stride=2, pad=7) + global average pool +
    bottleneck FC. Input (batch, 1, 16384) -> latent z (batch, 128)."""

    def __init__(self):
        super().__init__()
        channels = [1, 8, 16, 32, 64, 128, 128, 256, 256]
        layers = []
        for cin, cout in zip(channels[:-1], channels[1:]):
            layers += [
                nn.Conv1d(cin, cout, kernel_size=15, stride=2, padding=7),
                nn.BatchNorm1d(cout),
                nn.LeakyReLU(0.1),
            ]
        self.conv = nn.Sequential(*layers)
        self.pool = nn.AdaptiveAvgPool1d(1)
        self.bottleneck = nn.Sequential(
            nn.Linear(256, 256), nn.ReLU(), nn.Dropout(0.2),
            nn.Linear(256, 128),
        )

    def forward(self, x):
        # x: (batch, 1, 16384)
        h = self.conv(x)                 # (batch, 256, 64)
        h = self.pool(h).squeeze(-1)     # (batch, 256)
        z = self.bottleneck(h)           # (batch, 128)
        return z


class AuxMassHeads(nn.Module):
    """Option B: total_mass and eta, ordinary supervised regression,
    NOT tied to the PN residual or generator in either model."""

    def __init__(self):
        super().__init__()
        self.total_mass_head = nn.Sequential(nn.Linear(128, 64), nn.ReLU(), nn.Linear(64, 1))
        self.eta_head = nn.Sequential(nn.Linear(128, 64), nn.ReLU(), nn.Linear(64, 1))

    def forward(self, z):
        total_mass = _rescale_sigmoid(self.total_mass_head(z), MTOT_MIN, MTOT_MAX)
        eta = torch.sigmoid(self.eta_head(z)) * 0.25
        return total_mass.squeeze(-1), eta.squeeze(-1)


def recover_component_masses(total_mass, eta):
    """Post-hoc only (ARCHITECTURE_SPEC.md 4) -- never used in training."""
    eta = torch.clamp(eta, max=0.25)
    disc = torch.sqrt(torch.clamp(1 - 4 * eta, min=0))
    m1 = (total_mass / 2) * (1 + disc)
    m2 = (total_mass / 2) * (1 - disc)
    return m1, m2


class ChirpMassHead(nn.Module):
    def __init__(self):
        super().__init__()
        self.head = nn.Sequential(nn.Linear(128, 64), nn.ReLU(), nn.Linear(64, 1))

    def forward(self, z):
        return _rescale_sigmoid(self.head(z), MC_MIN, MC_MAX).squeeze(-1)


# ---------------------------------------------------------------------
# Soft-constrained model
# ---------------------------------------------------------------------

class Decoder(nn.Module):
    """Mirror of SharedEncoder: z (128) -> strain (16384), via FC expand +
    8 upsample+Conv1d blocks.

    GPU note: originally used ConvTranspose1d for upsampling. After
    extensive isolation testing (bisecting via DEBUG_SKIP_PHYSICS, and
    comparing against the hard model -- which shares SharedEncoder but has
    no Decoder, and trained 22 epochs on GPU with zero crashes), the
    evidence pointed specifically at ConvTranspose1d: it's the one op type
    used here that's never appeared in a successful GPU run. Transposed
    convolutions have a real, documented history of cuDNN backward-pass
    instability on certain GPU/driver/cuDNN combinations. Replaced with the
    standard alternative: parameter-free nearest-neighbor upsampling
    (no cuDNN backward path at all) + ordinary Conv1d (the same op type
    already proven stable in SharedEncoder). Slightly more parameters
    (extra Conv1d weights vs ConvTranspose1d's fused op) but functionally
    equivalent for this purpose, and avoids the suspect op entirely.
    """

    def __init__(self):
        super().__init__()
        self.fc_expand = nn.Linear(128, 256 * 64)
        channels = [256, 256, 128, 128, 64, 32, 16, 8, 1]
        layers = []
        for i, (cin, cout) in enumerate(zip(channels[:-1], channels[1:])):
            layers.append(nn.Upsample(scale_factor=2, mode="nearest"))
            layers.append(nn.Conv1d(cin, cout, kernel_size=15, stride=1, padding=7))
            if i < len(channels) - 2:  # no BN/activation on final layer
                layers += [nn.BatchNorm1d(cout), nn.LeakyReLU(0.1)]
        self.deconv = nn.Sequential(*layers)

    def forward(self, z):
        h = self.fc_expand(z).view(-1, 256, 64)
        strain = self.deconv(h).squeeze(1)   # (batch, 16384)
        return strain


class SoftConstrainedModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = SharedEncoder()
        self.decoder = Decoder()
        self.chirp_mass_head = ChirpMassHead()
        self.aux_heads = AuxMassHeads()

    def forward(self, noisy_strain):
        # noisy_strain: already scaled by STRAIN_SCALE
        z = self.encoder(noisy_strain.unsqueeze(1))
        recon_strain = self.decoder(z)
        chirp_mass = self.chirp_mass_head(z)
        total_mass, eta = self.aux_heads(z)
        return {
            "recon_strain": recon_strain,
            "chirp_mass": chirp_mass,
            "total_mass": total_mass,
            "eta": eta,
        }

    def physics_residual(self, recon_strain, chirp_mass):
        """Computed on the model's OWN reconstruction, per ARCHITECTURE_SPEC.md 2.3.

        Numerical safety (added after a real training blowup observed at
        w_physics=0.03): the previous version clamped dfdt_pn at 1e8 but
        normalized by DFDT_SCALE=3000, so even moderate PN df/dt values
        (1e4-1e5 Hz/s, realistic in this near-merger window) produced
        residual values in the thousands-to-millions -- enough to destroy
        the network in a single gradient step even at a small loss weight.
        Fixed with: (1) a tighter, more physically realistic dfdt_pn clamp,
        (2) a much larger DFDT_SCALE so typical-case residuals sit near
        O(1), and (3) an ELEMENTWISE clamp on the squared residual before
        averaging -- this bounds the worst-case contribution per sample
        while still preserving useful gradient from samples that aren't
        extreme outliers (a scalar clamp on the final mean would zero out
        gradient entirely whenever the batch-average exceeds the cap).
        """
        idx_lo = int(PHYSICS_WINDOW_T[0] / DELTA_T)
        idx_hi = int(PHYSICS_WINDOW_T[1] / DELTA_T)

        freq_full = instantaneous_frequency(recon_strain, DELTA_T)  
        freq_window = freq_full[:, idx_lo:idx_hi].contiguous()

        dfdt_numerical = (freq_window[:, 1:] - freq_window[:, :-1]) / DELTA_T
        freq_for_pn = freq_window[:, :-1]

        dfdt_pn = pn_dfdt(freq_for_pn, chirp_mass.unsqueeze(-1))
        dfdt_pn = torch.clamp(dfdt_pn, max=1e6)  # tightened from 1e8 

        normalized_sq_error = ((dfdt_numerical - dfdt_pn) / DFDT_SCALE) ** 2
        normalized_sq_error = torch.clamp(normalized_sq_error, max=25.0)  # per-element cap, preserves gradient below it
        residual = torch.mean(normalized_sq_error)
        return residual


# ---------------------------------------------------------------------
# Hard-constrained model
# ---------------------------------------------------------------------

class HardConstrainedModel(nn.Module):
    def __init__(self, seg_len=16384):
        super().__init__()
        self.encoder = SharedEncoder()
        self.chirp_mass_head = ChirpMassHead()
        self.phase_head = nn.Sequential(nn.Linear(128, 64), nn.ReLU(), nn.Linear(64, 2))  # (cos, sin)
        self.amplitude_head = nn.Sequential(nn.Linear(128, 64), nn.ReLU(), nn.Linear(64, 1))
        self.aux_heads = AuxMassHeads()
        self.register_buffer("t_grid", torch.linspace(0, seg_len * DELTA_T, seg_len))

    def forward(self, noisy_strain):
        z = self.encoder(noisy_strain.unsqueeze(1))
        chirp_mass = self.chirp_mass_head(z)

        cos_sin = self.phase_head(z)
        cos_sin = cos_sin / (cos_sin.norm(dim=-1, keepdim=True) + 1e-8)
        phi_c = torch.atan2(cos_sin[:, 1], cos_sin[:, 0])

        amplitude = _rescale_sigmoid(self.amplitude_head(z), A_MIN, A_MAX).squeeze(-1)
        total_mass, eta = self.aux_heads(z)

        recon_strain = self._generate(chirp_mass, phi_c, amplitude)

        return {
            "recon_strain": recon_strain,
            "chirp_mass": chirp_mass,
            "total_mass": total_mass,
            "eta": eta,
            "phi_c": phi_c,
            "amplitude": amplitude,
        }

    def _generate(self, chirp_mass, phi_c, amplitude):
        """The analytic PN generator -- ARCHITECTURE_SPEC.md 3.2. This IS the
        hard constraint: strain can only ever be a function that satisfies
        the leading-order PN frequency law, by construction."""
        batch = chirp_mass.shape[0]
        t = self.t_grid.unsqueeze(0).expand(batch, -1)          
        mchirp = chirp_mass.unsqueeze(-1)                        

        f_t = pn_frequency_of_time(t, T_COALESCENCE, mchirp)     

        # phase(t) = phi_c - integral_t^{t_c} 2*pi*f(t') dt'
        # implemented as: integral from 0 to t_c minus integral from 0 to t,
        # via cumulative trapezoidal integration
        omega = 2 * torch.pi * f_t
        dt = DELTA_T
        cum_phase = torch.cumsum(omega, dim=-1) * dt             # integral from 0 to t
        total_phase_to_tc = cum_phase[:, -1:]                    # approx integral 0 to t_c
        phase = phi_c.unsqueeze(-1) - (total_phase_to_tc - cum_phase)

        amp_envelope = amplitude.unsqueeze(-1) * f_t ** (2.0 / 3.0)
        strain = amp_envelope * torch.cos(phase)
        return strain

"""
Single self-contained cell: physics primitives + both PINN models + dataset
loading + training loop, all in one place. No argparse, no separate files --
just edit the CONFIG block below and run the cell.

Assumes dataset.npz is already present in the Colab filesystem (adjust
DATASET_PATH below to wherever you loaded it).
"""

import os
import csv
import time
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader


# =======================================================================
# CONFIG 
# =======================================================================
MODEL_TYPE = "soft"              
DATASET_PATH = "/content/drive/MyDrive/dataset (1).npz"     
OUTDIR = "checkpoints"
EPOCHS = 20
BATCH_SIZE = 32
PATIENCE = 15                    # early stopping patience (epochs)
LR = None                        # None -> use default (soft=1e-3, hard=5e-4)
W_MCHIRP = 1.0
W_AUX = 0.5
W_PHYSICS_MAX = 0.3              # soft model only
PHYSICS_WARMUP_START = 5         # soft model only
PHYSICS_WARMUP_END = 15          # soft model only
NUM_WORKERS = 2
LIMIT_SAMPLES = None             # set an int for a quick smoke test
DEBUG_SKIP_PHYSICS = False       # DEBUG


# =======================================================================
# SECTION 1: Physics primitives (differentiable torch port of physics_pn.py)
# =======================================================================

G = 6.674e-11
C = 2.998e8
MSUN_KG = 1.98892e30


def chirp_mass_to_kg(mchirp_msun):
    return mchirp_msun * MSUN_KG


def pn_dfdt(f, mchirp_msun):
    """Leading-order PN df/dt (Hz/s), differentiable w.r.t. both f and
    mchirp_msun. Shapes broadcast normally (e.g. f: [B, T], mchirp_msun: [B, 1])."""
    Mc = chirp_mass_to_kg(mchirp_msun)
    return (96.0 / 5.0) * torch.pi ** (8.0 / 3.0) * (G * Mc / C ** 3) ** (5.0 / 3.0) * f ** (11.0 / 3.0)


def pn_frequency_of_time(t, t_coalescence, mchirp_msun, f_max=400.0, tau_min=0.005):
    """Closed-form leading-order frequency-vs-time-to-merger track, with the
    numerical safeguards required for use inside a generator (see
    ARCHITECTURE_SPEC.md 3.3):
      - tau is floored at tau_min (5ms) to avoid the 1/tau singularity at t_c
      - f is capped at f_max (400 Hz) as a second line of defense

    t: [B, T] or [T] time grid (same for every sample in a batch, broadcastable)
    t_coalescence: python float (fixed constant for this dataset, not learned)
    mchirp_msun: [B, 1] predicted chirp mass per sample
    Returns: f(t), same shape as broadcast(t, mchirp_msun)
    """
    Mc = chirp_mass_to_kg(mchirp_msun)
    tau = t_coalescence - t
    tau_safe = torch.clamp(tau, min=tau_min)
    f = (1.0 / torch.pi) * (G * Mc / C ** 3) ** (-5.0 / 8.0) * (5.0 / (256.0 * tau_safe)) ** (3.0 / 8.0)
    f = torch.clamp(f, max=f_max)
    return f


def isco_frequency(total_mass_msun):
    Mtot = total_mass_msun * MSUN_KG
    return C ** 3 / (6.0 ** 1.5 * torch.pi * G * Mtot)


# ---------------------------------------------------------------------
# Differentiable instantaneous-frequency extraction (Hilbert transform via FFT)
# ---------------------------------------------------------------------

def instantaneous_frequency(strain, delta_t, smooth_kernel_width=25):
    """Estimate the instantaneous GW frequency of a real-valued strain
    signal via the analytic signal (Hilbert transform, computed with FFT so
    it stays differentiable), followed by phase unwrap and a finite
    difference. Used by the soft model's physics residual on its OWN
    reconstructed strain, so every operation here must support autograd.

    strain: [B, T] real-valued tensor
    Returns: freq [B, T-1] (Hz), one shorter than input due to the
             finite-difference derivative

    GPU note: tensors are forced .contiguous() before FFT/conv ops, the
    phase-unwrap correction avoids exact floating-point equality
    comparisons, and torch.gradient is replaced with a manual finite
    difference -- defensive fixes for a CUDA illegal-memory-access error
    traced to this function on GPU (never reproduced on CPU, but these are
    the least-standard ops in the whole pipeline and the most likely cause).
    """
    strain = strain.contiguous()
    strain = torch.nan_to_num(strain, nan=0.0, posinf=100.0, neginf=-100.0)  # defense in depth
    B, T = strain.shape

    # analytic signal via FFT: zero negative frequencies, double positive ones
    X = torch.fft.fft(strain, dim=-1)
    h = torch.zeros(T, device=strain.device, dtype=strain.dtype)
    if T % 2 == 0:
        h[0] = 1
        h[T // 2] = 1
        h[1:T // 2] = 2
    else:
        h[0] = 1
        h[1:(T + 1) // 2] = 2
    analytic = torch.fft.ifft(X * h, dim=-1).contiguous()

    phase = torch.atan2(analytic.imag, analytic.real).contiguous()  # [B, T], wrapped to (-pi, pi]

    # differentiable phase unwrap: correct jumps > pi by adding/subtracting 2*pi,
    # implemented via cumulative sum of the wrapped jump correction (standard
    # np.unwrap algorithm, re-expressed with torch ops so it's differentiable).
    # NOTE: the exact-equality edge case (dphase_wrapped == -pi) was removed --
    # exact float equality checks are fragile and were a suspected contributor
    # to GPU instability, for a branch that almost never triggers anyway.
    dphase = phase[:, 1:] - phase[:, :-1]
    dphase_wrapped = torch.remainder(dphase + torch.pi, 2 * torch.pi) - torch.pi
    correction = (dphase_wrapped - dphase).contiguous()
    phase_unwrapped = phase.clone()
    phase_unwrapped[:, 1:] = phase[:, 1:] + torch.cumsum(correction, dim=-1)
    phase_unwrapped = phase_unwrapped.contiguous()

    # manual finite difference instead of torch.gradient -- avoids relying
    # on torch.gradient's internal kernel behavior across torch/CUDA versions
    freq = (phase_unwrapped[:, 1:] - phase_unwrapped[:, :-1]) / (2 * torch.pi * delta_t)
    freq = freq.contiguous()

    # SANITIZE BEFORE the smoothing conv1d, not after. An untrained decoder
    # can produce near-arbitrary reconstructions, and raw finite-difference
    # frequency can be NaN/Inf as a result. 
    freq = torch.nan_to_num(freq, nan=0.0, posinf=2000.0, neginf=-2000.0)
    freq = torch.clamp(freq, min=-2000.0, max=2000.0).contiguous()

   
    # finite-difference noise, matching the rationale in Step 3 / ARCHITECTURE_SPEC 2.3
    if smooth_kernel_width > 1:
        kernel = torch.ones(1, 1, smooth_kernel_width, device=strain.device, dtype=strain.dtype) / smooth_kernel_width
        freq_padded = torch.nn.functional.pad(
            freq.unsqueeze(1), (smooth_kernel_width // 2, smooth_kernel_width // 2), mode="replicate")
        freq = torch.nn.functional.conv1d(freq_padded.contiguous(), kernel).squeeze(1)
        freq = freq[:, :phase_unwrapped.shape[1] - 1].contiguous()  # trim to match

    # final clamp to the physically sane band (redundant with the pre-conv
    # clamp in the common case, but cheap insurance either way)
    freq = torch.nan_to_num(freq, nan=1.0, posinf=2000.0, neginf=1.0)
    freq = torch.clamp(torch.abs(freq), min=1.0, max=2000.0)
    return freq


# =======================================================================
# SECTION 2: Model definitions
# =======================================================================

STRAIN_SCALE = 1e21
T_COALESCENCE = 3.5          
MC_MIN, MC_MAX = 5.0, 40.0
MTOT_MIN, MTOT_MAX = 20.0, 80.0
A_MIN, A_MAX = 0.1, 10.0
PHYSICS_WINDOW_T = (3.42, 3.50)   
DFDT_SCALE = 20000.0  
DELTA_T = 1.0 / 4096


def _rescale_sigmoid(raw, lo, hi):
    return lo + torch.sigmoid(raw) * (hi - lo)


class SharedEncoder(nn.Module):
    """8 Conv1d blocks (kernel=15, stride=2, pad=7) + global average pool +
    bottleneck FC. Input (batch, 1, 16384) -> latent z (batch, 128)."""

    def __init__(self):
        super().__init__()
        channels = [1, 8, 16, 32, 64, 128, 128, 256, 256]
        layers = []
        for cin, cout in zip(channels[:-1], channels[1:]):
            layers += [
                nn.Conv1d(cin, cout, kernel_size=15, stride=2, padding=7),
                nn.BatchNorm1d(cout),
                nn.LeakyReLU(0.1),
            ]
        self.conv = nn.Sequential(*layers)
        self.pool = nn.AdaptiveAvgPool1d(1)
        self.bottleneck = nn.Sequential(
            nn.Linear(256, 256), nn.ReLU(), nn.Dropout(0.2),
            nn.Linear(256, 128),
        )

    def forward(self, x):
        # x: (batch, 1, 16384)
        h = self.conv(x)                 
        h = self.pool(h).squeeze(-1)     
        z = self.bottleneck(h)           
        return z


class AuxMassHeads(nn.Module):
    """Option B: total_mass and eta, ordinary supervised regression,
    NOT tied to the PN residual or generator in either model."""

    def __init__(self):
        super().__init__()
        self.total_mass_head = nn.Sequential(nn.Linear(128, 64), nn.ReLU(), nn.Linear(64, 1))
        self.eta_head = nn.Sequential(nn.Linear(128, 64), nn.ReLU(), nn.Linear(64, 1))

    def forward(self, z):
        total_mass = _rescale_sigmoid(self.total_mass_head(z), MTOT_MIN, MTOT_MAX)
        eta = torch.sigmoid(self.eta_head(z)) * 0.25
        return total_mass.squeeze(-1), eta.squeeze(-1)


def recover_component_masses(total_mass, eta):
    """Post-hoc only (ARCHITECTURE_SPEC.md 4) -- never used in training."""
    eta = torch.clamp(eta, max=0.25)
    disc = torch.sqrt(torch.clamp(1 - 4 * eta, min=0))
    m1 = (total_mass / 2) * (1 + disc)
    m2 = (total_mass / 2) * (1 - disc)
    return m1, m2


class ChirpMassHead(nn.Module):
    def __init__(self):
        super().__init__()
        self.head = nn.Sequential(nn.Linear(128, 64), nn.ReLU(), nn.Linear(64, 1))

    def forward(self, z):
        return _rescale_sigmoid(self.head(z), MC_MIN, MC_MAX).squeeze(-1)


# ---------------------------------------------------------------------
# Soft-constrained model
# ---------------------------------------------------------------------

class Decoder(nn.Module):
    """Mirror of SharedEncoder: z (128) -> strain (16384), via FC expand +
    8 upsample+Conv1d blocks.

    GPU note: originally used ConvTranspose1d for upsampling. After
    extensive isolation testing (bisecting via DEBUG_SKIP_PHYSICS, and
    comparing against the hard model -- which shares SharedEncoder but has
    no Decoder, and trained 22 epochs on GPU with zero crashes), the
    evidence pointed specifically at ConvTranspose1d: it's the one op type
    used here that's never appeared in a successful GPU run. Transposed
    convolutions have a real, documented history of cuDNN backward-pass
    instability on certain GPU/driver/cuDNN combinations. Replaced with the
    standard alternative: parameter-free nearest-neighbor upsampling
    (no cuDNN backward path at all) + ordinary Conv1d (the same op type
    already proven stable in SharedEncoder). Slightly more parameters
    (extra Conv1d weights vs ConvTranspose1d's fused op) but functionally
    equivalent for this purpose, and avoids the suspect op entirely.
    """

    def __init__(self):
        super().__init__()
        self.fc_expand = nn.Linear(128, 256 * 64)
        channels = [256, 256, 128, 128, 64, 32, 16, 8, 1]
        layers = []
        for i, (cin, cout) in enumerate(zip(channels[:-1], channels[1:])):
            layers.append(nn.Upsample(scale_factor=2, mode="nearest"))
            layers.append(nn.Conv1d(cin, cout, kernel_size=15, stride=1, padding=7))
            if i < len(channels) - 2:  # no BN/activation on final layer
                layers += [nn.BatchNorm1d(cout), nn.LeakyReLU(0.1)]
        self.deconv = nn.Sequential(*layers)

    def forward(self, z):
        h = self.fc_expand(z).view(-1, 256, 64)
        strain = self.deconv(h).squeeze(1)   
        return strain


class SoftConstrainedModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = SharedEncoder()
        self.decoder = Decoder()
        self.chirp_mass_head = ChirpMassHead()
        self.aux_heads = AuxMassHeads()

    def forward(self, noisy_strain):
        # noisy_strain: already scaled by STRAIN_SCALE
        z = self.encoder(noisy_strain.unsqueeze(1))
        recon_strain = self.decoder(z)
        chirp_mass = self.chirp_mass_head(z)
        total_mass, eta = self.aux_heads(z)
        return {
            "recon_strain": recon_strain,
            "chirp_mass": chirp_mass,
            "total_mass": total_mass,
            "eta": eta,
        }

    def physics_residual(self, recon_strain, chirp_mass):
        """Computed on the model's OWN reconstruction, per ARCHITECTURE_SPEC.md 2.3.

        Numerical safety (added after a real training blowup observed at
        w_physics=0.03): the previous version clamped dfdt_pn at 1e8 but
        normalized by DFDT_SCALE=3000, so even moderate PN df/dt values
        (1e4-1e5 Hz/s, realistic in this near-merger window) produced
        residual values in the thousands-to-millions -- enough to destroy
        the network in a single gradient step even at a small loss weight.
        Fixed with: (1) a tighter, more physically realistic dfdt_pn clamp,
        (2) a much larger DFDT_SCALE so typical-case residuals sit near
        O(1), and (3) an ELEMENTWISE clamp on the squared residual before
        averaging -- this bounds the worst-case contribution per sample
        while still preserving useful gradient from samples that aren't
        extreme outliers (a scalar clamp on the final mean would zero out
        gradient entirely whenever the batch-average exceeds the cap).
        """
        idx_lo = int(PHYSICS_WINDOW_T[0] / DELTA_T)
        idx_hi = int(PHYSICS_WINDOW_T[1] / DELTA_T)

        freq_full = instantaneous_frequency(recon_strain, DELTA_T)  
        freq_window = freq_full[:, idx_lo:idx_hi].contiguous()

        dfdt_numerical = (freq_window[:, 1:] - freq_window[:, :-1]) / DELTA_T
        freq_for_pn = freq_window[:, :-1]

        dfdt_pn = pn_dfdt(freq_for_pn, chirp_mass.unsqueeze(-1))
        dfdt_pn = torch.clamp(dfdt_pn, max=1e6)  # tightened from 1e8 

        normalized_sq_error = ((dfdt_numerical - dfdt_pn) / DFDT_SCALE) ** 2
        normalized_sq_error = torch.clamp(normalized_sq_error, max=25.0)  # per-element cap, preserves gradient below it
        residual = torch.mean(normalized_sq_error)
        return residual


# ---------------------------------------------------------------------
# Hard-constrained model
# ---------------------------------------------------------------------

class HardConstrainedModel(nn.Module):
    def __init__(self, seg_len=16384):
        super().__init__()
        self.encoder = SharedEncoder()
        self.chirp_mass_head = ChirpMassHead()
        self.phase_head = nn.Sequential(nn.Linear(128, 64), nn.ReLU(), nn.Linear(64, 2))  # (cos, sin)
        self.amplitude_head = nn.Sequential(nn.Linear(128, 64), nn.ReLU(), nn.Linear(64, 1))
        self.aux_heads = AuxMassHeads()
        self.register_buffer("t_grid", torch.linspace(0, seg_len * DELTA_T, seg_len))

    def forward(self, noisy_strain):
        z = self.encoder(noisy_strain.unsqueeze(1))
        chirp_mass = self.chirp_mass_head(z)

        cos_sin = self.phase_head(z)
        cos_sin = cos_sin / (cos_sin.norm(dim=-1, keepdim=True) + 1e-8)
        phi_c = torch.atan2(cos_sin[:, 1], cos_sin[:, 0])

        amplitude = _rescale_sigmoid(self.amplitude_head(z), A_MIN, A_MAX).squeeze(-1)
        total_mass, eta = self.aux_heads(z)

        recon_strain = self._generate(chirp_mass, phi_c, amplitude)

        return {
            "recon_strain": recon_strain,
            "chirp_mass": chirp_mass,
            "total_mass": total_mass,
            "eta": eta,
            "phi_c": phi_c,
            "amplitude": amplitude,
        }

    def _generate(self, chirp_mass, phi_c, amplitude):
        """The analytic PN generator -- ARCHITECTURE_SPEC.md 3.2. This IS the
        hard constraint: strain can only ever be a function that satisfies
        the leading-order PN frequency law, by construction."""
        batch = chirp_mass.shape[0]
        t = self.t_grid.unsqueeze(0).expand(batch, -1)          
        mchirp = chirp_mass.unsqueeze(-1)                        

        f_t = pn_frequency_of_time(t, T_COALESCENCE, mchirp)     

        # phase(t) = phi_c - integral_t^{t_c} 2*pi*f(t') dt'
        # implemented as: integral from 0 to t_c minus integral from 0 to t,
        # via cumulative trapezoidal integration
        omega = 2 * torch.pi * f_t
        dt = DELTA_T
        cum_phase = torch.cumsum(omega, dim=-1) * dt             # integral from 0 to t
        total_phase_to_tc = cum_phase[:, -1:]                    # approx integral 0 to t_c
        phase = phi_c.unsqueeze(-1) - (total_phase_to_tc - cum_phase)

        amp_envelope = amplitude.unsqueeze(-1) * f_t ** (2.0 / 3.0)
        strain = amp_envelope * torch.cos(phase)
        return strain


# =======================================================================
# SECTION 3: Dataset
# =======================================================================

class StrainDataset(Dataset):
    def __init__(self, npz_path, split, limit=None):
        d = np.load(npz_path, allow_pickle=True)
        mask = d["split"] == split
        idx = np.where(mask)[0]
        if limit is not None:
            idx = idx[:limit]
        self.noisy = d["noisy"][idx]
        self.clean = d["clean"][idx]
        self.chirp_mass = d["chirp_mass"][idx].astype(np.float32)
        self.total_mass = d["total_mass"][idx].astype(np.float32)
        self.eta = d["eta"][idx].astype(np.float32)

    def __len__(self):
        return len(self.noisy)

    def __getitem__(self, i):
        return {
            "noisy": torch.tensor(self.noisy[i] * STRAIN_SCALE, dtype=torch.float32),
            "clean": torch.tensor(self.clean[i] * STRAIN_SCALE, dtype=torch.float32),
            "chirp_mass": torch.tensor(self.chirp_mass[i]),
            "total_mass": torch.tensor(self.total_mass[i]),
            "eta": torch.tensor(self.eta[i]),
        }


# =======================================================================
# SECTION 4: Loss functions
# =======================================================================

def soft_loss(model, out, batch, w_physics):
    data_loss = torch.nn.functional.mse_loss(out["recon_strain"], batch["clean"])
    mchirp_loss = torch.nn.functional.mse_loss(out["chirp_mass"], batch["chirp_mass"])
    # DEBUG_SKIP_PHYSICS lets us bisect the GPU crash
    if DEBUG_SKIP_PHYSICS:
        physics_loss = torch.tensor(0.0, device=out["recon_strain"].device)
    else:
        physics_loss = model.physics_residual(out["recon_strain"], out["chirp_mass"])
    aux_loss = (torch.nn.functional.mse_loss(out["total_mass"], batch["total_mass"])
                + torch.nn.functional.mse_loss(out["eta"], batch["eta"]))
    total = data_loss + W_MCHIRP * mchirp_loss + w_physics * physics_loss + W_AUX * aux_loss
    return total


def hard_loss(out, batch):
    data_loss = torch.nn.functional.mse_loss(out["recon_strain"], batch["clean"])
    mchirp_loss = torch.nn.functional.mse_loss(out["chirp_mass"], batch["chirp_mass"])
    aux_loss = (torch.nn.functional.mse_loss(out["total_mass"], batch["total_mass"])
                + torch.nn.functional.mse_loss(out["eta"], batch["eta"]))
    total = data_loss + W_MCHIRP * mchirp_loss + W_AUX * aux_loss
    return total


def physics_weight_schedule(epoch):
    if epoch < PHYSICS_WARMUP_START:
        return 0.0
    if epoch >= PHYSICS_WARMUP_END:
        return W_PHYSICS_MAX
    return W_PHYSICS_MAX * (epoch - PHYSICS_WARMUP_START) / (PHYSICS_WARMUP_END - PHYSICS_WARMUP_START)


def run_epoch(model, loader, device, optimizer, w_physics, train):
    model.train() if train else model.eval()
    total_loss, total_mchirp_err, n_samples = 0.0, 0.0, 0

    context = torch.enable_grad() if train else torch.no_grad()
    with context:
        for batch in loader:
            batch = {k: v.to(device) for k, v in batch.items()}
            if train:
                optimizer.zero_grad()

            out = model(batch["noisy"])
            if MODEL_TYPE == "soft":
                loss = soft_loss(model, out, batch, w_physics)
            else:
                loss = hard_loss(out, batch)

            if train:
                loss.backward()
                # gradient clipping for BOTH models now (was hard-only) --
                # a real run showed the soft model's physics term can also
                # produce catastrophic gradient spikes when w_physics turns on
                max_norm = 1.0 if MODEL_TYPE == "hard" else 5.0
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=max_norm)
                optimizer.step()

            bs = batch["noisy"].shape[0]
            total_loss += loss.item() * bs
            rel_err_pct = (torch.abs(out["chirp_mass"] - batch["chirp_mass"]) / batch["chirp_mass"]) * 100
            total_mchirp_err += rel_err_pct.sum().item()
            n_samples += bs

    return total_loss / n_samples, total_mchirp_err / n_samples


# =======================================================================
# SECTION 5: Run training
# =======================================================================

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

train_ds = StrainDataset(DATASET_PATH, "train", limit=LIMIT_SAMPLES)
val_ds = StrainDataset(DATASET_PATH, "val", limit=LIMIT_SAMPLES)
print(f"Train samples: {len(train_ds)}, Val samples: {len(val_ds)}")

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,
                           num_workers=NUM_WORKERS, drop_last=True)
val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False,
                         num_workers=NUM_WORKERS)

if MODEL_TYPE == "soft":
    model = SoftConstrainedModel().to(device)
    lr = LR if LR is not None else 1e-3
else:
    model = HardConstrainedModel().to(device)
    lr = LR if LR is not None else 5e-4

n_params = sum(p.numel() for p in model.parameters())
print(f"Model: {MODEL_TYPE}-constrained, {n_params:,} parameters, lr={lr}")

optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=1e-5)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, factor=0.5, patience=8)

os.makedirs(OUTDIR, exist_ok=True)
log_path = f"{OUTDIR}/{MODEL_TYPE}_training_log.csv"
ckpt_path = f"{OUTDIR}/{MODEL_TYPE}_model.pt"

fieldnames = ["epoch", "train_loss", "val_loss", "val_mchirp_err_pct", "lr"]
if MODEL_TYPE == "soft":
    fieldnames.append("w_physics")
with open(log_path, "w", newline="") as f:
    csv.writer(f).writerow(fieldnames)

best_val_loss = float("inf")
epochs_without_improvement = 0
t_start = time.time()

for epoch in range(EPOCHS):
    t_epoch = time.time()

    w_physics = physics_weight_schedule(epoch) if MODEL_TYPE == "soft" else None

    train_loss, train_mchirp_err = run_epoch(model, train_loader, device, optimizer, w_physics, train=True)
    val_loss, val_mchirp_err = run_epoch(model, val_loader, device, optimizer, w_physics, train=False)

    scheduler.step(val_loss)
    current_lr = optimizer.param_groups[0]["lr"]

    row = [epoch, train_loss, val_loss, val_mchirp_err, current_lr]
    if MODEL_TYPE == "soft":
        row.append(w_physics)
    with open(log_path, "a", newline="") as f:
        csv.writer(f).writerow(row)

    improved = val_loss < best_val_loss
    if improved:
        best_val_loss = val_loss
        epochs_without_improvement = 0
        torch.save({"model_state_dict": model.state_dict(), "epoch": epoch, "val_loss": val_loss},
                   ckpt_path)
    else:
        epochs_without_improvement += 1

    elapsed_epoch = time.time() - t_epoch
    elapsed_total = time.time() - t_start
    physics_str = f"  w_physics={w_physics:.3f}" if MODEL_TYPE == "soft" else ""
    marker = "  <- best" if improved else ""
    print(f"epoch {epoch:3d}/{EPOCHS}  train_loss={train_loss:10.4f}  val_loss={val_loss:10.4f}  "
          f"val_mchirp_err={val_mchirp_err:5.2f}%  lr={current_lr:.2e}{physics_str}  "
          f"({elapsed_epoch:.1f}s/epoch, {elapsed_total/60:.1f}min total){marker}")

    if epochs_without_improvement >= PATIENCE:
        print(f"Early stopping: no val improvement for {PATIENCE} epochs.")
        break

print(f"\nDone. Best val_loss={best_val_loss:.4f}. Checkpoint: {ckpt_path}. Log: {log_path}")